//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eventual.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_SETTINGS
    {
        public string SALT { get; set; }
        public int MAX_EVENTS_PER_USER { get; set; }
    }
}
